FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --upgrade pip --no-cache-dir

COPY requirements.tkinter.txt .
RUN pip install --no-cache-dir -r requirements.tkinter.txt

COPY app/ .

CMD ["python", "main.py"]
