ALTER TABLE document MODIFY COLUMN type_document
  ENUM('CNI','PASSEPORT','PV_POLICE','CERTIFICAT_MEDICAL','FACTURE_MEDICALE',
       'PHOTO_ACCIDENT','ATTESTATION_ASSURANCE','RIB','AUTRE','LETTRE_DECISION',
       'QUITTANCE','DEMANDE_PROVISION')
  NOT NULL;
